# Generated by Django 4.0.6 on 2022-07-20 06:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Membership',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('membership_name', models.CharField(max_length=100)),
                ('membership_description', models.CharField(max_length=240)),
                ('membership_price_1_month', models.CharField(max_length=8)),
                ('membership_price_3_month', models.CharField(max_length=8)),
                ('membership_price_6_month', models.CharField(max_length=8)),
                ('membership_price_12_month', models.CharField(max_length=8)),
                ('membership_price_24_month', models.CharField(max_length=8)),
                ('membership_image', models.ImageField(blank=True, upload_to='membership_images/')),
            ],
        ),
        migrations.CreateModel(
            name='Ovauser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Ovauser_name', models.CharField(max_length=100)),
                ('Ovauser_password', models.CharField(max_length=8)),
                ('Ovauser_email', models.EmailField(max_length=254)),
                ('Ovauser_phone', models.CharField(max_length=10)),
                ('Ovauser_dni', models.CharField(max_length=8)),
                ('Ovauser_birthday', models.DateField()),
                ('Ovauser_fingerprint', models.ImageField(blank=True, upload_to='fingerprint_images/')),
                ('Ovauser_membership_ini', models.DateField()),
                ('Ovauser_membership_end', models.DateField()),
                ('Ovamembership_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='test04.membership')),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_name', models.CharField(max_length=100)),
                ('product_description', models.CharField(max_length=100)),
                ('product_price', models.CharField(max_length=8)),
                ('product_image', models.ImageField(blank=True, upload_to='product_images/')),
            ],
        ),
        migrations.CreateModel(
            name='Routine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('routine_name', models.CharField(max_length=100)),
                ('routine_description', models.CharField(max_length=100)),
                ('routine_date', models.DateField()),
                ('routine_duration', models.TimeField()),
            ],
        ),
        migrations.CreateModel(
            name='Ovauser_debt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Ovauser_debt_date', models.DateField()),
                ('Ovauser_debt_description', models.CharField(max_length=100)),
                ('Ovauser_debt_Ovauser_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='test04.ovauser')),
                ('Ovauser_debt_product_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='test04.product')),
            ],
        ),
        migrations.AddField(
            model_name='ovauser',
            name='Ovaroutine_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='test04.routine'),
        ),
    ]
