# Generated by Django 4.0.6 on 2022-07-20 06:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('test04', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='ovauser_debt',
            name='Ovauser_debt_note',
            field=models.CharField(default=0, max_length=100),
            preserve_default=False,
        ),
    ]
