# Generated by Django 4.0.6 on 2022-07-17 19:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Member',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('member_name', models.CharField(max_length=100)),
                ('member_birthday', models.CharField(max_length=100)),
                ('member_ini', models.DateField()),
                ('member_end', models.TimeField()),
            ],
        ),
        migrations.CreateModel(
            name='Rotuine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('routine_name', models.CharField(max_length=100)),
                ('routine_description', models.CharField(max_length=100)),
                ('routine_date', models.DateField()),
                ('routine_time', models.TimeField()),
                ('member_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ova01.member')),
            ],
        ),
    ]
