# Generated by Django 4.0.6 on 2022-07-17 19:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ova01', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Rotuine',
            new_name='Routine',
        ),
    ]
