# Generated by Django 4.0.6 on 2022-07-20 04:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ova01', '0002_rename_rotuine_routine'),
    ]

    operations = [
        migrations.AddField(
            model_name='member',
            name='member_dni',
            field=models.CharField(default=0, max_length=8),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='member',
            name='member_birthday',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='member',
            name='member_end',
            field=models.DateField(),
        ),
    ]
